### ISSUE TITLE
Error when running pynt videocature[]

### ISSUE THREAD

**Issue by DawnMKing** [aws-samples/amazon-rekognition-video-analyzer#27]
I have completed and can run the pipeline, however, I keep getting this streaming error when my webcam turns on. The http://localhost:8080/ does nothing, but my video turn on and I can see myself on a pop up screen. I am not sure where to go from here...

<img width="1113" alt="screen shot 2018-03-29 at 4 53 36 pm" src="https://user-images.githubusercontent.com/21011198/38115473-c9aafa70-3371-11e8-8311-f5705575841b.png">

**Comment by moanany** [comment]
Hey @DawnMKing,

It seems like video frames are not captured or transferred by the video capture client, and that's why you don't see output in the Web UI. You may want to set a breakpoint in the videocapture client code and debug to see where it fails. This could lead us to the issue. What version of Python are you using?
